version: "3.8"

services:
  vendure-server:
    build: .
    command: npm run start:server
    ports:
      - "3000:3000"
    env_file:
      - .env

  vendure-worker:
    build: .
    command: npm run start:worker
    env_file:
      - .env