services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server  # Build the server image
    depends_on:
      - worker
    volumes:
      - config:/app/config
      - /srv/vendure/admin-ui:/usr/src/app/admin-ui  # Mount pre-built admin-ui here
    env_file:
      - .env
    networks:
      - coolify

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker  # Build the worker image
    volumes:
      - config:/app/config
    env_file:
      - .env
    networks:
      - coolify

volumes:
  config:

networks:
  coolify:
    external: true